Repository drush-ops/drush, pull requests merged in 2018-10, with the labels that each got.

#3685 bugfix in pgsql sql driver : options --data-only and --create-db were always active
  src/Sql/SqlPgsql.php
Labels: area-postgres, type-bug

#2973 GH-492: Fixes PGPASSFILE error as not an internal or external command
  src/Sql/SqlPgsql.php
Labels: area-postgres, area-sql, area-windows

#3656 Drush 8.x: Adding cwd option to core-cli
  commands/core/cli.drush.inc
Labels: area-psysh
