Repository drush-ops/drush, pull requests merged in 2022-01, with the labels that each got.

#4860 Minimize .phar size
  box.json.dist
  composer.json
Labels: drush8

#4834 Convert migrate tests to integration tests
  .docker/zz-php.ini
  docs/commands.md
  docs/deploycommand.md
  docs/generators.md
  src/Drupal/Commands/core/EntityCommands.php
  src/Drupal/Commands/core/MigrateRunnerCommands.php
  src/Drupal/Migrate/MigrateExecutable.php
  src/Drupal/Migrate/MigrateUtils.php
  tests/fixtures/modules/woot/composer.json
  tests/fixtures/modules/woot/drush.services.yml
  tests/fixtures/modules/woot/migrations/test_migration.yml
  tests/fixtures/modules/woot/migrations/test_migration_source_issues.yml
  tests/fixtures/modules/woot/migrations/test_migration_tagged.yml
  tests/fixtures/modules/woot/migrations/test_migration_untagged.yml
  tests/fixtures/modules/woot/src/Commands/AnnotatedGreetCommand.php
  tests/fixtures/modules/woot/src/Commands/GreetCommand.php
  tests/fixtures/modules/woot/src/Commands/WootCommands.php
  tests/fixtures/modules/woot/src/Controller/WootController.php
  tests/fixtures/modules/woot/src/DependingService.php
  tests/fixtures/modules/woot/src/EventSubscriber/ConfigSubscriber.php
  tests/fixtures/modules/woot/src/EventSubscriber/PreRowDeleteTestSubscriber.php
  tests/fixtures/modules/woot/src/EventSubscriber/ProcessRowTestSubscriber.php
  tests/fixtures/modules/woot/src/Generators/ExampleGenerator.php
  tests/fixtures/modules/woot/src/Generators/example-generator.twig
  tests/fixtures/modules/woot/src/Plugin/QueueWorker/CustomException.php
  tests/fixtures/modules/woot/src/Plugin/QueueWorker/WootCustomException.php
  tests/fixtures/modules/woot/src/Plugin/QueueWorker/WootRequeueException.php
  tests/fixtures/modules/woot/src/Plugin/migrate/process/TestFailProcess.php
  tests/fixtures/modules/woot/src/Plugin/migrate/source/TestSourceWithMissedRequirements.php
  tests/fixtures/modules/woot/src/WootCommandInfoAlterer.php
  tests/fixtures/modules/woot/src/WootManager.php
  tests/fixtures/modules/woot/woot.deploy.php
  tests/fixtures/modules/woot/woot.info.yml
  tests/fixtures/modules/woot/woot.install
  tests/fixtures/modules/woot/woot.module
  tests/fixtures/modules/woot/woot.post_update.php
  tests/fixtures/modules/woot/woot.routing.yml
  tests/fixtures/modules/woot/woot.services.yml
  tests/functional/CommandInfoAlterTest.php
  tests/functional/ConfigTest.php
  tests/functional/ContainerTest.php
  tests/functional/DeployHookTest.php
  tests/functional/QueueTest.php
  tests/functional/UpdateDBTest.php
  tests/integration/MigrateRunnerTest.php
  tests/integration/ModuleGeneratorTest.php
Labels: stat-ready-to-review, area-migrate

#4973 PHP 8.1 deprecations
  composer.json
  composer.lock
  src/Commands/core/RsyncCommands.php
  src/Drupal/Commands/core/DrupalCommands.php
  src/Preflight/Preflight.php
Labels: stat-ready-to-review

#4980 Inject migration plugin manager
  src/Drupal/Commands/core/EntityCommands.php
  src/Drupal/Commands/core/MigrateRunnerCommands.php
  src/Drupal/Commands/core/drush.services.yml
  src/Drupal/Migrate/MigrateExecutable.php
  src/Drupal/Migrate/MigrateIdMapFilter.php
  src/Drupal/Migrate/MigrateMissingSourceRowsEvent.php
  src/Drupal/Migrate/MigratePrepareRowEvent.php
  src/Drupal/Migrate/MigrateUtils.php
Labels: stat-ready-to-review, area-migrate

#5053 Fix usage example in core:route command
  src/Drupal/Commands/core/DrupalCommands.php
Labels: type-bug

#5050 Don't blacklist internal/symfony
  box.json.dist
Labels: drush8
